config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :tools, only: [:index, :show, :destroy] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only:[] do
    member do
      patch :confirm
      patch :refuse
    end
  end
  resources :my_tools
  resource :profile, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :tool
  has_one_attached :photo
end

app/models/tool.rb
class Tool < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tools
  has_many :bookings
  has_many :bookings_as_owner, through: :tools
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @tool = Tool.find(params[:tool_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @tool = Tool.find(params[:tool_id])
    @booking.tool = @tool
    @booking.user = current_user
    @booking.price_to_invoice = (@booking.end_date - @booking.begin_date).to_i / 1.day * @tool.daily_price

    if @booking.save
     redirect_to profile_path, notice: 'Votre demande de réservation est envoyée au propriétaire et en attente de confirmation'
     else
     render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    booking = Booking.find(params[:id])
    booking.update(booking_params)
    redirect_to booking_path(booking)
  end

  def confirm
    booking = Booking.find(params[:id])
    booking.status = "confirmed"
    booking.save
    redirect_to profile_path, notice: 'Vous avez confirmé ce booking'
  end

  def refuse
    booking = Booking.find(params[:id])
    booking.status = "declined"
    booking.save
    redirect_to profile_path, notice: 'Vous avez refusé ce booking'
  end

  private

  def booking_params
    params.require(:booking).permit(:begin_date, :end_date, :status, :price_to_invoice, :photo)
  end
end

app/controllers/my_tools_controller.rb
class MyToolsController < ApplicationController
  def index
    @my_tools = current_user.tools
    Tool.where(user: current_user)
  end

  def show
    @my_tool = Tool.find(params[:id])
  end

  def new
    @my_tool = Tool.new
  end

  def create
    @my_tool = Tool.new(my_tool_params)
    @my_tool.user = current_user
    if @my_tool.save
      redirect_to my_tools_path(@my_tool)
    else
      render :new
    end
  end

  def edit
    @my_tool = Tool.find(params[:id])
  end

  # def update
  #   my_tool = Tool.find(params[:id])
  #   my_tool.update(tool_params)
  #   redirect_to my_tool_path(@my_tool)
  # end

  def update
    @tool = Tool.find(params[:id])
    if @tool.update(my_tool_params)
      redirect_to @tool, notice: 'Tool was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @tool.destroy
    redirect_to my_tools, notice: 'Tool was successfully destroyed.'
  end

  private

  def my_tool_params
    params.require(:tool).permit(:daily_price, :location, :description, :name, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = current_user
    @my_own_bookings = @user.bookings.order(begin_date: :desc) #je suis locataire
    @my_tools = @user.tools
    # @bookings = @user.bookings_as_owner
    @bookings = Booking.joins(:tool).where(tools: { user: current_user }).order(begin_date: :desc) #je suis proprio
  end
end


# <<~SQL
# select * FROM bookings JOIN tools ON bookings.tool_id = tools.id
# WHERE tools.user_id = current_user.id
# SQL

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @tools = Tool.all
    @tools = @tools.where.not(user_id: current_user.id) if current_user
    @markers = @tools.geocoded.map do |tool|
      {
        lat: tool.latitude,
        lng: tool.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { tool: tool })
      }
    end
  end

  def show
    @tool = Tool.find(params[:id])
  end

  def destroy
    @my_tool = Tool.find(params[:id])
    @my_tool.destroy
    redirect_to my_tools_url, notice: 'Tool was successfully destroyed.'
  end

  private

  def tool_params
    params.require(:tool).permit(:daily_price, :location, :description, :name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_helper.rb
module BookingHelper
  def french_status(booking)
    case booking.status
    when "declined"  then "refusée"
    when "pending"   then "en attente"
    when "confirmed" then "acceptée"
    end
  end
end

app/views/bookings/_form.html.erb
<%= simple_form_for(tool) do |f| %>
<%= f.input :photo, as: :file %>
<% end %>

app/views/bookings/confirmation.html.erb
<h1>ca marche </h1>

app/views/bookings/new.html.erb
<h1>Réservez votre tondeuse à gazon !</h1>

<%# <%= cl_image_tag @tool.photo.key, height: 300, width: 400, crop: :fill %>
<!-- .class.downcase.pluralize => @review -> reviews -->
<div class="container">
  <div class="col-sm-8 offset-sm-2 new-form-tool">
    <div class="text-form-tool">
    <h2>Entrez vos dates de location</h2>
      <%= simple_form_for [@tool, @booking] do |f| %>
      <%= f.input :begin_date, as: :date, html5: true %>
      <%= f.input :end_date, as: :date, html5: true %>
      <%= f.submit "Réserver" %>
      <% end %>
      </div>
    </div>
</div>
<!-- <form action="/restaurants/2/reviews" method="post">
  <label for="content">Content</label>
  <input type="text" name="content">
</form>
 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tools</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Hotjar Tracking Code for https://www.mamiebetty.com -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:2137534,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>


    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>

  </body>
</html>

app/views/my_tools/edit.html.erb
<h1>Editing My Tool</h1>

<div class=‘container’>
  <%= simple_form_for @my_tool, url: my_tool_path(@my_tool), method: :patch do |f| %>
    <%= f.input :name %>
    <%= f.input :location %>
    <%= f.input :description %>
    <%= f.input :daily_price %>
    <%= f.input :photo %>

    <%= f.submit %>
  <% end %>
</div>

app/views/my_tools/index.html.erb
<!-- my_tools index.html.erb  -->
<h1 class="m-3"> All my tools </h1>

  <!-- <div class="my-tools">
 <% @my_tools.each do |tool| %>
  <div class="card-product zoom">
    <%= cl_image_tag tool.photo.key , crop: :fill ,width: 190%>
    <div class="card-product-infos">
      <h2 class="tag"><%= link_to(tool.name, tool_path(tool))%></h2>
      <h2 class="tag">City:<%= link_to(tool.location, tool_path(tool))%></h2>
      <p>Infos:<%= tool.description %></p>
      <p>Fee per day: <%= tool.daily_price %> Euros</p>
      <p class="tag"><%= link_to 'Destroy', tool, method: :delete, data: { confirm: 'Are you sure?' } %></p>
      <p class="tag"><%= link_to 'Edit', new_my_tool_path%></p>
    </div>
  </div>
<% end %>
</div> -->

<div align="center">
  <div style="width:700px;">
    <% @my_tools.each do |tool| %>
  <div class="card-product style_prevu_kit">
    <%= cl_image_tag tool.photo.key , crop: :fill ,width: 190%>
    <div class="card-product-infos">
      <h2 class="tag"><%= link_to(tool.name, tool_path(tool))%></h2>
      <h2 class="tag">Ville:<%= link_to(tool.location, tool_path(tool))%></h2>
      <p>Infos:<%= tool.description %></p>
      <p>Fee per day: <%= tool.daily_price %> Euros</p>
      <p class="tag1 btn-del-edit"><%= link_to 'Supprimer', tool, method: :delete, data: { confirm: 'Are you sure?' } %></p>
      <p class="tag1 btn-del-edit"><%= link_to 'Modifier', new_my_tool_path%></p>
    </div>
  </div>
<% end %>
  </div>
</div>

app/views/my_tools/new.html.erb
<div class=‘container’>
  <div class="col-sm-8 offset-sm-2 new-form-tool">
    <div class="text-form-tool">
      <%= simple_form_for @my_tool, url: my_tools_path do |f| %>
      <%= f.input :name %>
      <%= f.input :location %>
      <%= f.input :description %>
      <%= f.input :daily_price %>
      <%= f.input :photo %>
        <div class="btn-submit">
          <%= f.submit %>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
  <body>
  <div class= "container">
  <br>
  <div class="hometitle">
  <h1>WELCOME TO TOOLS!</h1>
  </div>
<br>
  <div class= "banner">
    <%= image_tag "tondeuse-home-tools.jpg", alt: "tondeuse", class: "homepic" %>
   <div class="text">
      <h2>LOUEZ VOTRE TONDEUSE <br>AUX PORTES DE VOTRE JARDIN</h2>
   </div>
   <%# <a href="https://tools.cleverapps.io/tools" class="btn btn-info" role="button">VOIR LES TONDEUSES</a> %>
   <%= link_to "VOIR LES TONDEUSES", "tools", class: "btn btn-flat" %>
  </div>

  <div class="flex-container">
    <div class="flex-item">LOUEZ LOCALEMENT <i class="fas fa-map-marked-alt"></i></div>
    <div class="flex-item">LOUEZ IMMEDIATEMENT <i class="fas fa-tachometer-alt"></i></div>
    <div class="flex-item">LOUEZ ASTUCIEUSEMENT <i class="fas fa-clipboard-check"></i></div>
  </div>
<br>
<%= image_tag "logo-carre-vert.png", alt: "logo-tools", class: "logo-gros" %>
<br>
<br>

<div class="explication">
  <h2>TOOLS, pour les jardiniers du dimanche au samedi !</h2>
</div>
  <div class= "introduction"> <p>Vous n'avez pas de tondeuse.<br>Vous ne voulez pas en posséder une car vous estimez que son usage est trop occasionnel.<br>Vous voulez tondre votre pelouse demain mais votre tondeuse est cassée.<br>
Vous êtes jardinier amateur ou passionné.<br><strong>TOOLS vous permet de louer une tondeuse entre particulier, localement, immédiatement et astucieusement !</strong></p></div>
<br>
<br>

<div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(https://us.123rf.com/450wm/rastudio/rastudio1601/rastudio160102332/50784123-un-agriculteur-conduisant-un-vecteur-de-tracteur-design-plat-illustration-isol%C3%A9-sur-fond-blanc-.jpg?ver=6)">
    <h3>Tondeuse autoportée</h3><p>POUR ENTRETENIR LES GRANDS ESPACES<p>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(https://image.freepik.com/vecteurs-libre/jardinier-homme-tondeuse-gazon_1366-613.jpg)">
    <h3>Tondeuse manuelle</h3><p>POUR JARDINER EN SILENCE<p>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(https://static.vecteezy.com/system/resources/previews/000/424/547/non_2x/vector-farmer-man-cutting-grass-with-mower.jpg)">
    <h3>Tondeuse électrique</h3><p>POUR MANOEUVRER FACILEMENT<p>
  </div>
</div>
<br>
<br>
<br>


  <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>




  </div>
  </body>
</html>

app/views/profiles/show.html.erb
<h1> MON PROFILE </h1>

<div class="container">
  <div class="titre">
    <p><%= @user.email %></p>
  </div>
  <br>
  <br>
  <br>
  <div class="historique">
    <div class = "titre">
      <h2> Historique des tondeuses que j'ai louées </h2>
    </div>
    <div class= "para tag">
      <ul>
        <% if @my_own_bookings.present? %>
           <% @my_own_bookings.each do |booking| %>
           <li> <%= link_to(booking.tool.name, tool_path(booking.tool))%> - Louée à partir de <%= booking.begin_date.strftime("%d/%m/%Y") %> - Pour un total de <%= booking.price_to_invoice%> Euros
          <% end %>
           </li>
        <% else %>
        Vous n'avez pas encore d'historique.
        <% end  %>
    </ul>
  </div>


  <br>
  <br>

  <!-- here add an Event listener so that the status changes and the btns disappear -->
  <div class="Mes tondeuses">
    <div class="titre">
    <h2> Historique des locations de mes tondeuses</h2></div>
    <div class="para">
    <ul>
      <% @bookings.each do |booking| %>
      <div class="d-flex justify-content-between" >

        <div class="date tag"> <li><%= link_to(booking.tool.name, tool_path(booking.tool))%> - du <%= booking.begin_date.strftime("%d/%m/%Y") %> au <%= booking.end_date.strftime("%d/%m/%Y") %></div>
        <div>demande <%= french_status(booking) %></div>
        <div class="status">   <%= link_to "accepter", confirm_booking_path(booking), method: :patch, class: 'btn btn-success' %> <%= link_to "refuser",refuse_booking_path(booking), method: :patch, class: 'btn btn-danger' %></div></li>
      </div>
     <% end %>
    </ul>
  </div>


</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-color">
  <%= link_to "/", class: "avatar-navbar navbar-brand" do %>
    <%# <%= image_tag "https://png.pngtree.com/png-vector/20190909/ourlarge/pngtree-lawn-mower-isolated-simple-element-illustration-from-cleaning-lawn-png-image_1726697.jpg" %>
    <%= image_tag "logo-carre.png", alt: "logo" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active search">

          <p class="tag-nav nav-link m-3 btn-login"><%= link_to "Voir mes tondeuses", my_tools_path%></p>
          <p class="tag-nav nav-link m-3 btn-login"><%= link_to "Voir mes réservations", profile_path%></p>
          <p class="tag-nav nav-link m-3 btn-login"><%= link_to "Ajouter une tondeuse en location",new_my_tool_path%></p>
        </li>
        <li class="nav-item">
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://avatarfiles.alphacoders.com/207/thumb-207370.jpg", class: "zoom avatar dropdown-toggle m-3", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right menu-avatar" aria-labelledby="navbarDropdown">
            <%= link_to "    Profil", profile_path, class: "dropdown-item fas fa-user m-2" %>
            <%= link_to "    Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item fas fa-sign-out-alt m-2" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link btn-login" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/tools/_form.html.erb
<%= simple_form_for(tool) do |f| %>
<%= f.input :photo, as: :file %>
<% end %>

app/views/tools/_info_window.html.erb
<!-- _info_window.html.erb -->
<p><%= link_to(tool.name, tool_path(tool))%></p>
<p><%= tool.location %></p>

app/views/tools/index.html.erb
<!-- index.html.erb -->
<br>
<h1> VOICI LES TONDEUSES DISPONIBLES </h1>
<br>
<br>

<div class='container'>
 <div class='tool-index'>
   <div id="map"
       style="width: 50%; height: 600px;"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

   <div class='tool-cards'>
      <% @tools.each do |tool| %>
       <div class="card-product">
         <%= cl_image_tag tool.photo.key %>
          <div class="card-product-infos">
           <h2 class="tag"><%= link_to(tool.name, tool_path(tool))%></h2>
           <div class= "description">
           <p><i class="fas fa-question"></i>  <%= tool.description %></p></div>
           <div class= "price">
           <p><i class="fas fa-euro-sign"></i> <%= tool.daily_price %> / jour</p></div>
           <div class = "location">
           <p><i class="fas fa-search-location"></i>  <%=tool.location%></p></div>
          </div>
       </div>
     <% end %>
    <div>
  <div>
</div>

</div>

app/views/tools/show.html.erb
<!-- <div>
  <div class="card mb-3 card-show">
    <img class="image-show" <%= cl_image_tag @tool.photo.key %>>
    <div class="card-body">
      <h5 class="card-title"><%=@tool.name%></h5>
      <p class="card-text"><%=@tool.description%></p>
      <p class="card-text"><small class="text-muted"><%=@tool.daily_price%>€</small></p>
    </div>
  </div>
</div> -->
<h1><%=@tool.name%></h1>
<p class="tag back-list m-32"><%= link_to "Retour à la liste", tools_path%></p>
<div class="container">
  <ul class="main">
    <li class="cards_item-tool">
      <div class="card-tool main">
        <div class="card_image"><img class="image-show" <%= cl_image_tag @tool.photo.key %>
        </div>
        <div class="card_content-tool">
          <p class="card_text-tool"><%=@tool.description%></p>
          <p class="card_text-tool">Prix par jour:     <%=@tool.daily_price%>€</p>
          <%= link_to "JE LOUE", new_tool_booking_path(@tool) , class: "btn btn-flat" %>
        </div>
      </div>
    </ul>
</div>